SELECT 
	PER.PARTY_ID ,
	PER.FIRST_NAME ,
	RI.ORDER_ID
FROM
	RETURN_ITEM RI
 JOIN RETURN_HEADER RH
ON
	RH.RETURN_ID = RI.RETURN_ID and 
	MONTH(RH.ENTRY_DATE) = MONTH(CURRENT_DATE()) - 1
	and YEAR(RH.ENTRY_DATE) = YEAR(CURRENT_DATE())
JOIN PERSON PER
ON
	PER.PARTY_ID = RH.FROM_PARTY_ID
GROUP BY
	RI.ORDER_ID,
	RH.FROM_PARTY_ID
HAVING
	COUNT(RI.ORDER_ID) = 1
ORDER BY
	PER.PARTY_ID