select
	IT.FACILITY_ID as FROM_FACILITY,
	IT.FACILITY_ID_TO as TO_FACILITY,
	II.PRODUCT_ID ,
	IT.STATUS_ID ,
	IT.RECEIVE_DATE ,
	IT.QUANTITY as REQUESTED_QUANTITY,
	II2.TRANSFER_QUANTITY as RESERVED_QUANTITY,
	II2.ORDER_ID
FROM inventory_transfer IT
left join inventory_item II
on IT.INVENTORY_ITEM_ID = II.INVENTORY_ITEM_ID 
left join item_issuance II2
on II2.INVENTORY_ITEM_ID = II.INVENTORY_ITEM_ID 