select
	OH.ORDER_ID ,
	OH.ORDER_DATE ,
	OH.STATUS_ID ,
	OH.ENTRY_DATE,
	OH.SALES_CHANNEL_ENUM_ID ,
	OH.PRODUCT_STORE_ID ,
	P.PRODUCT_ID ,
	P.PRODUCT_TYPE_ID ,
	PT.IS_PHYSICAL
from
	(
	select
		*
	from
		ORDER_HEADER
	where
		STATUS_ID in ('ORDER_CREATED', 'ORDER_APPROVED')) OH
left join ORDER_STATUS OS
on
	OS.ORDER_ID = OH.ORDER_ID
	and OS.STATUS_ID = OH.STATUS_ID
left join ORDER_ITEM OI
on
	OI.ORDER_ID = OH.ORDER_ID
join PRODUCT P
on
	OI.PRODUCT_ID = P.PRODUCT_ID
join PRODUCT_TYPE PT
on
	PT.PRODUCT_TYPE_ID = P.PRODUCT_TYPE_ID