SELECT 
	COUNT(RI.RETURN_QUANTITY) AS TOTAL_RETURNS,
	SUM(RI.RETURN_QUANTITY * RI.RETURN_PRICE) AS RETURNS_TOTAL,
	COUNT(RA.RETURN_ADJUSTMENT_ID) TOTAL_APPEASEMENT,
	SUM(RA.AMOUNT) AS APPEASEMENT_TOTAL
FROM
	RETURN_HEADER RH
LEFT JOIN RETURN_ADJUSTMENT RA
ON
	RA.RETURN_ID = RH.RETURN_ID
	AND RA.RETURN_ADJUSTMENT_TYPE_ID = 'APPEASEMENT'
LEFT JOIN RETURN_ITEM RI
ON
	RI.RETURN_ID = RH.RETURN_ID