select 
	RH.RETURN_ID,
	RH.RETURN_DATE ,
	RH.ENTRY_DATE ,
	RA.RETURN_ADJUSTMENT_TYPE_ID ,
	(RI.RETURN_PRICE * RI.RETURN_QUANTITY ) as AMOUNT,
	RA.COMMENTS ,
	RI.ORDER_ID ,
	OH.ORDER_DATE ,
	OH.PRODUCT_STORE_ID 
from return_header RH
left join return_item RI
on RI.RETURN_ID = RH.RETURN_ID 
LEFT JOIN RETURN_ADJUSTMENT RA
ON RH.RETURN_ID = RA.RETURN_ID 
left join ORDER_HEADER OH
on OH.ORDER_ID = RI.ORDER_ID
order by RH.RETURN_ID
