SELECT 
	RH.RETURN_ID ,
	RH.FROM_PARTY_ID ,
	RH.ENTRY_DATE ,
	RH.RETURN_CHANNEL_ENUM_ID ,
	RI.RETURN_ITEM_SEQ_ID ,
	OH.ORDER_ID ,
	OH.PRODUCT_STORE_ID ,
	RS.STATUS_DATETIME ,
	RS.STATUS_ID
FROM
	RETURN_ITEM RI
LEFT JOIN RETURN_HEADER RH
ON
	RH.RETURN_ID = RI.RETURN_ID
LEFT JOIN ORDER_HEADER OH
ON
	OH.ORDER_ID = RI.ORDER_ID
LEFT JOIN RETURN_STATUS RS
ON
	RS.RETURN_ID = RI.RETURN_ID
	AND RS.RETURN_ITEM_SEQ_ID = RI.RETURN_ITEM_SEQ_ID
	AND RS.STATUS_ID = RI.STATUS_ID
ORDER BY
	RI.RETURN_ID