select
	FP.FACILITY_ID ,
	PT.PARTY_ID ,
	PT.STATUS_ID ,
	FP.ROLE_TYPE_ID ,
	PER.FIRST_NAME ,
	PER.LAST_NAME
from
	FACILITY_PARTY FP
left join PARTY PT
on
	FP.PARTY_ID = PT.PARTY_ID
left join PERSON PER
on
	PER.PARTY_ID = PT.PARTY_ID
where
	FP.THRU_DATE is not null
	or FP.THRU_DATE > CURRENT_DATE()
	and FP.FROM_DATE < CURRENT_DATE()