select
	COUNT(OSG.ORDER_ID),
	FC.FACILITY_ID ,
	FC.FACILITY_NAME ,
	DATE(MIN(OSG.CREATED_STAMP)) as FROM_DATE,
	DATE(MAX(OSG.CREATED_STAMP)) as TO_DATE
from order_item_ship_group OSG
left join facility FC
on FC.FACILITY_ID = OSG.FACILITY_ID 
where OSG.SHIPMENT_METHOD_TYPE_ID = 'NEXT_DAY'
and MONTH(OSG.CREATED_STAMP) = MONTH(CURRENT_DATE()) - 1
	and YEAR(OSG.CREATED_STAMP) = YEAR(CURRENT_DATE())
group by FC.FACILITY_ID
order by COUNT(OSG.ORDER_ID) desc
limit 1
